import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Auto-generated by `prisma generate` (prisma/schema.prisma's `output`)
    // — large enough (wasm-bindgen glue, generated model types) that eslint
    // OOM'd trying to lint it before this was added.
    "generated/**",
    ".open-next/**",
    ".wrangler/**",
    // Auto-generated by `wrangler types` — regenerate with `npm run cf:types`.
    "worker-configuration.d.ts",
  ]),
]);

export default eslintConfig;
